### ISSUE TITLE
Check for grammatical mistakes

### ISSUE THREAD

**Issue by thesohelshaikh** [thesohelshaikh/hacknirma#8]

**Comment by nahuelhm17** [comment]
Hello, I would like to contribute to this. I'm not a native speaker, but I think that I can do my bit.

**Comment by thesohelshaikh** [comment]
You can read the [contributing](https://github.com/thesohelshaikh/hacknirma/CONTRIBUTING.md) guidlines if you are new to this. 

If you are not comfortable with pull requests then you can directly comment here. Thanks! 😄

**Comment by vvyomjjain** [comment]
#10

**Comment by thesohelshaikh** [comment]
@vvyomjjain Did you check for mistakes in whole file?

**Comment by vvyomjjain** [comment]
@thesohelshaikh No, it is a big file. I can do that later if I find some time. Thanks by the way for creating this repo.

**Comment by thesohelshaikh** [comment]
👍 @vvyomjjain
